apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandbox-deployment
  labels:
    app: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sandbox
  template:
    metadata:
      labels:
        app: sandbox
    spec:
      containers:
      - name: sandbox
        image: jessemillar/sandbox:latest
